name: run-focussed
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      httpImplementation:
        description: 'HTTP Implementation'
        default: 'impl'
        required: true
        
jobs:
  run-focussed-tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./focused
    strategy:
      matrix:
        java: [ '17' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: 'maven'
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for Focussed
      run: mvn -B -DskipTests=true install
    - name: Run Focussed
      run: mvn -amd -B verify -Dglassfish.keepServerRunning
  
